"use strict";
let anyEstaDeVolta;
anyEstaDeVolta = 3;
anyEstaDeVolta = 'teste';
anyEstaDeVolta = 5;
let stringTest = 'verificar';
stringTest = anyEstaDeVolta;
let unknowValor;
unknowValor = 3;
unknowValor = 'Opa';
unknowValor = true;
unknowValor = 'vai sim';
let stringTest2 = 'agora vai';
stringTest2 = unknowValor;
